# Generated by Django 5.1 on 2024-08-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=230)),
                ('book_price', models.IntegerField()),
                ('book_image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'book_table',
            },
        ),
    ]
